# Generated by Django 4.2.2 on 2023-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='home_type',
            field=models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homepost',
            name='bath_rooms',
            field=models.IntegerField(verbose_name='Bath Rooms'),
        ),
    ]
