# Generated by Django 4.2.2 on 2023-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
