# Generated by Django 4.2.2 on 2023-07-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_reset_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password_toekn',
            new_name='forget_password_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
    ]
